---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pizza-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pizza-operator
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - org.acme
  resources:
  - pizzaoperatorcustomresources
  verbs:
  - "*"
- apiGroups:
  - org.acme
  resources:
  - pizzaoperatorcustomresources/status
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pizza-operator
subjects:
- kind: ServiceAccount
  name: pizza-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: pizza-operator
  apiGroup: ""